project:
  type: website

website:
  title: "Porfolio"
  navbar:
    left:
      - text: "R-Visual Analytics"
        menu: 
          - text: "Project 01"
            href: "R-VAA/Project01/Project01.html"
          - text: "Project 02"
            href: "R-VAA/Project02/Project02.html" 
          - text: "Project 03"
            href: "R-VAA/Project03/Project03.html"
      - text: "R-Shiny Project"
        menu: 
          - text: "Proposal"
            href: "R-Shiny/Proposal/Proposal.html"
          - text: "Prototype"
            href: "R-Shiny/Prototype/Prototype.html" 
          - text: "Shiny App"
            href: "https://haductien1211.shinyapps.io/MC3ShinyAppDemo/"
          - text: "User Guide"
            href: "User Guide/User_guide.html"
      - text: "R-Geospatial Analytics"
        menu: 
          - text: "Project 01"
            href: "R-GAA/Project01/Project01.html" 
          - text: "Project 02"
            href: "R-GAA/Project02/Project02.html" 
          - text: "Project 03"
            href: "R-GAA/Project03/Project03.html" 
      # - text: "Python"
      #   menu: 
      #     - text: "Project 1"               
    right: 
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: Zephyr
      dark: darkly
    css: styles.css
    toc: true
    toc-location: left
    grid: 
      body-width: 1500px
      sidebar-width: 300px
      margin-width:	150px

