<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ha Duc Tien">
<meta name="dcterms.date" content="2024-10-21">

<title>Project 3 – Porfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7466ca754ed477131903e1e4901f413b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-fb5288b925de641b8023f14ac5c0aea5.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">



<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Porfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-visual-analytics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R-Visual Analytics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-visual-analytics">    
        <li>
    <a class="dropdown-item" href="../../R-VAA/Project01/Project01.html">
 <span class="dropdown-text">Project 01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../R-VAA/Project02/Project02.html">
 <span class="dropdown-text">Project 02</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../R-VAA/Project03/Project03.html">
 <span class="dropdown-text">Project 03</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-shiny-project" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R-Shiny Project</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-shiny-project">    
        <li>
    <a class="dropdown-item" href="../../R-Shiny/Proposal/Proposal.html">
 <span class="dropdown-text">Proposal</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../R-Shiny/Prototype/Prototype.html">
 <span class="dropdown-text">Prototype</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://haductien1211.shinyapps.io/MC3ShinyAppDemo/">
 <span class="dropdown-text">Shiny App</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../User Guide/User_guide.html">
 <span class="dropdown-text">User Guide</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-geospatial-analytics" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R-Geospatial Analytics</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-r-geospatial-analytics">    
        <li>
    <a class="dropdown-item" href="../../R-GAA/Project01/Project01.html">
 <span class="dropdown-text">Project 01</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../R-GAA/Project02/Project02.html">
 <span class="dropdown-text">Project 02</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../R-GAA/Project03/Project03.html">
 <span class="dropdown-text">Project 03</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-python" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Python</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-python">    
        <li class="dropdown-header">Project 1</li>
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#objectives-and-tasks-and-packages-used" id="toc-objectives-and-tasks-and-packages-used" class="nav-link active" data-scroll-target="#objectives-and-tasks-and-packages-used">1. Objectives and Tasks and packages used</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">2. The data</a></li>
  <li><a href="#data-prepratation-and-wrangling" id="toc-data-prepratation-and-wrangling" class="nav-link" data-scroll-target="#data-prepratation-and-wrangling">3. Data prepratation and wrangling</a>
  <ul class="collapse">
  <li><a href="#first-phase-of-data-preparation-and-wrangling" id="toc-first-phase-of-data-preparation-and-wrangling" class="nav-link" data-scroll-target="#first-phase-of-data-preparation-and-wrangling">3.1 First phase of data preparation and wrangling</a>
  <ul class="collapse">
  <li><a href="#resale-data" id="toc-resale-data" class="nav-link" data-scroll-target="#resale-data">Resale data</a></li>
  <li><a href="#cbd-data" id="toc-cbd-data" class="nav-link" data-scroll-target="#cbd-data">CBD data</a></li>
  <li><a href="#mall-list" id="toc-mall-list" class="nav-link" data-scroll-target="#mall-list">Mall list</a></li>
  <li><a href="#primary-school-list" id="toc-primary-school-list" class="nav-link" data-scroll-target="#primary-school-list">Primary school list</a></li>
  <li><a href="#mrt" id="toc-mrt" class="nav-link" data-scroll-target="#mrt">MRT</a></li>
  <li><a href="#preschool-location" id="toc-preschool-location" class="nav-link" data-scroll-target="#preschool-location">Preschool location</a></li>
  <li><a href="#kindergartens" id="toc-kindergartens" class="nav-link" data-scroll-target="#kindergartens">Kindergartens</a></li>
  <li><a href="#supermarkets" id="toc-supermarkets" class="nav-link" data-scroll-target="#supermarkets">Supermarkets</a></li>
  <li><a href="#eldercare-center" id="toc-eldercare-center" class="nav-link" data-scroll-target="#eldercare-center">Eldercare center</a></li>
  <li><a href="#childcare-center" id="toc-childcare-center" class="nav-link" data-scroll-target="#childcare-center">Childcare center</a></li>
  <li><a href="#bus-stops" id="toc-bus-stops" class="nav-link" data-scroll-target="#bus-stops">Bus Stops</a></li>
  <li><a href="#chas-clinics" id="toc-chas-clinics" class="nav-link" data-scroll-target="#chas-clinics">CHAS clinics</a></li>
  <li><a href="#market-and-foodcentres" id="toc-market-and-foodcentres" class="nav-link" data-scroll-target="#market-and-foodcentres">Market and foodcentres</a></li>
  <li><a href="#parks" id="toc-parks" class="nav-link" data-scroll-target="#parks">Parks</a></li>
  </ul></li>
  <li><a href="#second-phase-of-data-preparation-and-wrangling" id="toc-second-phase-of-data-preparation-and-wrangling" class="nav-link" data-scroll-target="#second-phase-of-data-preparation-and-wrangling">3.2 Second phase of data preparation and wrangling</a></li>
  <li><a href="#third-phase-of-data-preparation-and-wrangling" id="toc-third-phase-of-data-preparation-and-wrangling" class="nav-link" data-scroll-target="#third-phase-of-data-preparation-and-wrangling">3.3 Third phase of data preparation and wrangling</a></li>
  </ul></li>
  <li><a href="#model-bulding-and-callibation" id="toc-model-bulding-and-callibation" class="nav-link" data-scroll-target="#model-bulding-and-callibation">4. Model bulding and callibation</a>
  <ul class="collapse">
  <li><a href="#non-spatial-multiple-linear-regression" id="toc-non-spatial-multiple-linear-regression" class="nav-link" data-scroll-target="#non-spatial-multiple-linear-regression">4.1 Non-spatial multiple linear regression</a></li>
  <li><a href="#geographically-weighted-regression-with-gwr-method" id="toc-geographically-weighted-regression-with-gwr-method" class="nav-link" data-scroll-target="#geographically-weighted-regression-with-gwr-method">4.2 Geographically Weighted Regression with gwr method</a></li>
  <li><a href="#geographically-weighted-random-forest-method-of-spatialml-package" id="toc-geographically-weighted-random-forest-method-of-spatialml-package" class="nav-link" data-scroll-target="#geographically-weighted-random-forest-method-of-spatialml-package">4.3 Geographically Weighted Random Forest method of SpatialML package</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">5. Conclusion</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project 3</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ha Duc Tien </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 21, 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">January 29, 2025</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="objectives-and-tasks-and-packages-used" class="level1">
<h1>1. Objectives and Tasks and packages used</h1>
<p>In this project, I planned to calibrate a predictive model to predict HDB resale prices between July-September 2024 by using HDB resale transaction records in 2023. For the purpose of this take-home exercise, HDB Resale Flat Prices provided by Data.gov.sg should be used as the core data set. The study should focus on either three-room, four-room or five-room flat.</p>
<p>https://isss626-ay2024-25aug.netlify.app/take-home_ex03b</p>
<p>The below packages are used and loaded in using the <code>p_load()</code> function of <code>pacman</code> package</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, sf, httr, jsonlite, tmap, SpatialAcc, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               spdep, GWmodel, SpatialML, rsample, Metrics, kableExtra,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               knitr, ggstatsplot, spatstat, see, performance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-data" class="level1">
<h1>2. The data</h1>
<p>Below is a list of predictors and data used in this study</p>
<p>Structural factors all of this are locate within the <a href="https://data.gov.sg/datasets/d_8b84c4ee58e3cfc0ece0d773c8ca6abc/view">Resale flat prices based on registration date from Jan-2017 onwards</a> under the <em>resale.csv</em> file - Area of the unit - Floor level - Remaining lease</p>
<p>Locational factors</p>
<ul>
<li>Proxomity to CBDs based on the <a href="https://data.gov.sg/datasets/d_d14da225fccf921049ab64238ff473d9/view">Master Plan 2014 Subzone Boundary (Web)</a></li>
<li>Proximity to eldercares from Eldercare Services (SHP) <a href="https://data.gov.sg/datasets/d_3545b068e3f3506c56b2cb6b6117b884/view">data.gov.sg</a></li>
<li>Proximity to market/food centres is based on NEA Market and Food Centre from <a href="https://data.gov.sg/datasets/d_a57a245b3cf3ec76ad36d55393a16e97/view">data.gov.sg</a></li>
<li>Proximity to MRTs or MRTs exit points are based on LTA MRT Station Exit (GEOJSON) from <a href="https://data.gov.sg/datasets/d_b39d3a0871985372d7e1637193335da5/view">data.gov.sg</a></li>
<li>Proximity to parks based on the Parks from NPARKS (National Parks Board) from <a href="https://data.gov.sg/datasets/d_0542d48f0991541706b58059381a6eca/view">data.gov.sg</a></li>
<li>Proximity to shopping malls this is based on a list of shopping malls namaes extracted from <a href="https://en.wikipedia.org/wiki/List_of_shopping_malls_in_Singapore">Wikipedia</a></li>
<li>Proximity to supermarkets based on the Supermarkets (KML) from SFA (Singapore Food Agency) from <a href="https://data.gov.sg/datasets/d_8a77ee0446716b2ce475a587004afc73/view">data.gov.sg</a></li>
<li>Numbers of kindergartens within 350m from the Kindergartens data from ECDA (Early Childhood Development Agency) from <a href="https://data.gov.sg/datasets/d_95aa63998d7de94dd4cb3e8e43a5f6d5/view">data.gov.sg</a></li>
<li>Numbers of childcare centres within 350m probabably based on the Child Care Services from <a href="https://data.gov.sg/datasets/d_5d668e3f544335f8028f546827b773b4/view">data.gov.sg</a>, but the actual data was from <a href="https://r4gdsa.netlify.app/chap04.html#the-data">Chapter 4</a></li>
<li>Numbers of bus stops within 350m data is based on the Bus Stops data from LTA <a href="https://datamall.lta.gov.sg/content/datamall/en/dynamic-data.html">datamall</a></li>
<li>Numbers of preschools within 350m based on Pre-Schools Location data from ECDA (Early Childhood Development Agency) from <a href="https://data.gov.sg/datasets/d_61eefab99958fd70e6aab17320a71f1c/view">data.gov.sg</a></li>
<li>Numbers of CHAS within 1km based on the CHAS Clinics data from MOH (Ministry of Health) from <a href="https://data.gov.sg/datasets/d_65d11d02ab0246cec53bfc995c782628/view">data.gov.sg</a></li>
<li>Numbers of primary schools within 1km The data of schools is gotten from the <a href="https://data.gov.sg/datasets/d_688b934f82c1059ed0a6993d2a829089/view">data.gov.sg</a> website that has a list of all schools and their addresses</li>
</ul>
</section>
<section id="data-prepratation-and-wrangling" class="level1">
<h1>3. Data prepratation and wrangling</h1>
<section id="first-phase-of-data-preparation-and-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="first-phase-of-data-preparation-and-wrangling">3.1 First phase of data preparation and wrangling</h2>
<section id="resale-data" class="level3">
<h3 class="anchored" data-anchor-id="resale-data">Resale data</h3>
<p>First the resale data will be loaded into data call <code>resale</code> using the <code>read_cvs()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>resale <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/non-geo/resale.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(month <span class="sc">&gt;=</span> <span class="st">"2023-01"</span> <span class="sc">&amp;</span> month <span class="sc">&lt;=</span> <span class="st">"2024-09"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(resale)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
  month town  flat_type block street_name storey_range floor_area_sqm flat_model
  &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;                 &lt;dbl&gt; &lt;chr&gt;     
1 2023… ANG … 2 ROOM    406   ANG MO KIO… 01 TO 03                 44 Improved  
2 2023… ANG … 2 ROOM    323   ANG MO KIO… 04 TO 06                 49 Improved  
3 2023… ANG … 2 ROOM    314   ANG MO KIO… 04 TO 06                 44 Improved  
4 2023… ANG … 2 ROOM    314   ANG MO KIO… 07 TO 09                 44 Improved  
5 2023… ANG … 2 ROOM    170   ANG MO KIO… 01 TO 03                 45 Improved  
6 2023… ANG … 3 ROOM    225   ANG MO KIO… 04 TO 06                 67 New Gener…
# ℹ 3 more variables: lease_commence_date &lt;dbl&gt;, remaining_lease &lt;chr&gt;,
#   resale_price &lt;dbl&gt;</code></pre>
</div>
</div>
<p>First look at the data we could see that there is a range of story under <code>storey_range</code> and <code>remaining_lease</code> are actully a string instead of numeric data that need to be convert to a better data for better modelling later. Other data such as <code>floor_area_sqm</code> and <code>resale_price</code> seems to be in appropriate</p>
<p>Quickly checking unique data for <code>storey_range</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(resale<span class="sc">$</span>storey_range)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "01 TO 03" "04 TO 06" "07 TO 09" "25 TO 27" "10 TO 12" "13 TO 15"
 [7] "16 TO 18" "22 TO 24" "19 TO 21" "34 TO 36" "28 TO 30" "37 TO 39"
[13] "31 TO 33" "40 TO 42" "43 TO 45" "46 TO 48" "49 TO 51"</code></pre>
</div>
</div>
<p>There is 17 unique data which I’ll convert to numeric from 1-17 separately..</p>
<p>The <code>remaining_lease</code> would go through being separate into <code>remaining_lease_yr</code> column and <code>remaining_lease_mth</code> separated then recalculate under <code>remaining_lease_time</code> with function <code>remaining_lease_yr</code>*12 + <code>remaining_lease_mth</code>.</p>
<p>All of the above steps would be done with the code below creating <code>resale_tidy</code> data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>resale_tidy <span class="ot">&lt;-</span> resale <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">address =</span> <span class="fu">paste</span>(block,street_name)) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">remaining_lease_yr =</span> <span class="fu">as.integer</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_sub</span>(remaining_lease, <span class="dv">0</span>, <span class="dv">2</span>)))<span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">remaining_lease_mth =</span> <span class="fu">as.integer</span>(</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">str_sub</span>(remaining_lease, <span class="dv">9</span>, <span class="dv">11</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.numeric , replace_na, <span class="at">replace =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">remaining_lease_time =</span> remaining_lease_yr<span class="sc">*</span><span class="dv">12</span> <span class="sc">+</span> remaining_lease_mth) <span class="sc">%&gt;%</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">storey_level =</span>  <span class="fu">case_when</span>(</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"01 TO 03"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">1</span>),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"04 TO 06"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">2</span>),</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"07 TO 09"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">3</span>),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"10 TO 12"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">4</span>),</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"13 TO 15"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">5</span>),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"16 TO 18"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">6</span>),</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"19 TO 21"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">7</span>),</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"22 TO 24"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">8</span>),</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"25 TO 27"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">9</span>),</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"28 TO 30"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">10</span>),</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"31 TO 33"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">11</span>),</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"34 TO 36"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">12</span>),</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"37 TO 39"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">13</span>),</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"40 TO 42"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">14</span>),</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"43 TO 45"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">15</span>),</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"46 TO 48"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">16</span>),</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    storey_range <span class="sc">==</span> <span class="st">"49 TO 51"</span> <span class="sc">~</span> <span class="fu">as.integer</span>(<span class="dv">17</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now with the basic resale data sort, we would next need to find the geographical location of each of these units, to do this I would first need to get the list of <code>address</code> of these units, using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>add_list <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(resale_tidy<span class="sc">$</span>address))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This function below is used to make and API call to <a href="https://www.onemap.gov.sg">onemap</a> API to extract the coordinate of these units based on its address, this would later be used based on names of shopping malls as well which I will mention.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>get_coords <span class="ot">&lt;-</span> <span class="cf">function</span>(add_list){</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Create a data frame to store all retrieved coordinates</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  postal_coords <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> add_list){</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="co">#print(i)</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    r <span class="ot">&lt;-</span> <span class="fu">GET</span>(<span class="st">'https://www.onemap.gov.sg/api/common/elastic/search?'</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">query=</span><span class="fu">list</span>(<span class="at">searchVal=</span>i,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">returnGeom=</span><span class="st">'Y'</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">getAddrDetails=</span><span class="st">'Y'</span>))</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    data <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">rawToChar</span>(r<span class="sc">$</span>content))</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    found <span class="ot">&lt;-</span> data<span class="sc">$</span>found</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    res <span class="ot">&lt;-</span> data<span class="sc">$</span>results</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create a new data frame for each address</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    new_row <span class="ot">&lt;-</span> <span class="fu">data.frame</span>()</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If single result, append </span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (found <span class="sc">==</span> <span class="dv">1</span>){</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>      postal <span class="ot">&lt;-</span> res<span class="sc">$</span>POSTAL </span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>      lat <span class="ot">&lt;-</span> res<span class="sc">$</span>LATITUDE</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>      lng <span class="ot">&lt;-</span> res<span class="sc">$</span>LONGITUDE</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>      new_row <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">address=</span> i, </span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>                            <span class="at">postal =</span> postal, </span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>                            <span class="at">latitude =</span> lat, </span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>                            <span class="at">longitude =</span> lng)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If multiple results, drop NIL and append top 1</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span> <span class="cf">if</span> (found <span class="sc">&gt;</span> <span class="dv">1</span>){</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Remove those with NIL as postal</span></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>      res_sub <span class="ot">&lt;-</span> res[res<span class="sc">$</span>POSTAL <span class="sc">!=</span> <span class="st">"NIL"</span>, ]</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Set as NA first if no Postal</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (<span class="fu">nrow</span>(res_sub) <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>          new_row <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">address=</span> i, </span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>                                <span class="at">postal =</span> <span class="cn">NA</span>, </span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>                                <span class="at">latitude =</span> <span class="cn">NA</span>, </span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>                                <span class="at">longitude =</span> <span class="cn">NA</span>)</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>      <span class="cf">else</span>{</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>        top1 <span class="ot">&lt;-</span> <span class="fu">head</span>(res_sub, <span class="at">n =</span> <span class="dv">1</span>)</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>        postal <span class="ot">&lt;-</span> top1<span class="sc">$</span>POSTAL </span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>        lat <span class="ot">&lt;-</span> top1<span class="sc">$</span>LATITUDE</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>        lng <span class="ot">&lt;-</span> top1<span class="sc">$</span>LONGITUDE</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>        new_row <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">address=</span> i, </span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>                              <span class="at">postal =</span> postal, </span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>                              <span class="at">latitude =</span> lat, </span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>                              <span class="at">longitude =</span> lng)</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span> {</span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>      new_row <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">address=</span> i, </span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>                            <span class="at">postal =</span> <span class="cn">NA</span>, </span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a>                            <span class="at">latitude =</span> <span class="cn">NA</span>, </span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a>                            <span class="at">longitude =</span> <span class="cn">NA</span>)</span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Add the row</span></span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a>    postal_coords <span class="ot">&lt;-</span> <span class="fu">rbind</span>(postal_coords, new_row)</span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-66"><a href="#cb9-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(postal_coords)</span>
<span id="cb9-67"><a href="#cb9-67" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once the function is loaded and the unit address list is created, the below code chunk is run to get all the geo coordinates of these units</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">get_coords</span>(add_list)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Just in case I will write these coords to a rds file for later usage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(coords, <span class="st">"data/rds/coords.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/coords.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These coordinates is then joined back to the <code>resale_tidy</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>resale_tidy <span class="ot">&lt;-</span> resale_tidy <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(coords)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since the coords would appear as <code>longitude</code> and <code>latitude</code> which is not <code>sf</code> type and would be hard for later analysis, the code chunk below would use the <code>st_as_sf()</code> to convert it to a <strong>POINT</strong> geometric instead, then to make sure the <code>crs</code> is in correct format of 3414 I will also use <code>st_transform()</code>. This code chunk below would create <code>resale_tidy_final</code> data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>resale_tidy_final <span class="ot">&lt;-</span> resale_tidy <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Just in case I will write this data to a rds file for later usage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(resale_tidy_final, <span class="st">"data/rds/resale_tidy_final.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>resale_tidy_final <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/resale_tidy_final.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, since the study would be focusing on either 3 rooms, 4 rooms or 5 rooms units using 2023 data to predict July-September 2024 data. In this case I would be focusing on 3 rooms analysis and did one more wrangling to filter data to only include 2023 - Sep 2024 and for 3 room units.</p>
<p>The code chunk below is for this wrangling process</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>resale_final <span class="ot">&lt;-</span> resale_tidy_final <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(flat_type <span class="sc">==</span> <span class="st">'3 ROOM'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(month <span class="sc">&gt;=</span> <span class="st">"2023-01"</span> <span class="sc">&amp;</span> month <span class="sc">&lt;=</span> <span class="st">"2024-09"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cbd-data" class="level3">
<h3 class="anchored" data-anchor-id="cbd-data">CBD data</h3>
<p>CBD data is using the Master Plan 2014 Subzone Boundary (Web) which I would load and then filter out only the CBD region which includes ‘DOWNTOWN CORE’, ‘MARINA EAST’, ‘MARINA SOUTH’, ‘MUSEUM’, ‘NEWTON’, ‘ORCHARD’, ‘OUTRAM’, ‘RIVER VALLEY’, ‘ROCHOR’, ‘SINGAPORE RIVER’, ‘STRAITS VIEW’, <code>st_transform()</code> would also be used just in case in the code chunk below creating the <code>CBD</code> data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>CBD <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geo"</span>, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">layer =</span> <span class="st">"MP14_SUBZONE_WEB_PL"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PLN_AREA_N <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'DOWNTOWN CORE'</span>, <span class="st">'MARINA EAST'</span>, <span class="st">'MARINA SOUTH'</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'MUSEUM'</span>, <span class="st">'NEWTON'</span>, <span class="st">'ORCHARD'</span>, <span class="st">'OUTRAM'</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'RIVER VALLEY'</span>, <span class="st">'ROCHOR'</span>, <span class="st">'SINGAPORE RIVER'</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>                           <span class="st">'STRAITS VIEW'</span>))<span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mall-list" class="level3">
<h3 class="anchored" data-anchor-id="mall-list">Mall list</h3>
<p>Since the data is extracted from Wikipedia and only include the mall names, I would need to somehow get the coordinates for these malls. But first the mall list is loaded in creating <code>mall_list</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mall_list <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/non-geo/mall_list.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Similarly to the <code>resale</code> data I wil once again get the <code>unique</code> list of <code>name</code> instead of address this time with the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>mall_name <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(mall_list<span class="sc">$</span>name))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then this name list would be feed into the <code>get_coords()</code> function creating a new list of coordinations that has the name of the malls and its coords as <code>longitude</code> and <code>latitude</code> which is not <code>sf</code> type and would be hard for later analysis, the code chunk below would use the <code>st_as_sf()</code> to convert it to a <strong>POINT</strong> geometric instead and <code>st_transform()</code> used to make sure the crs is in correct format. All of this would be done in the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mall_list_coords <span class="ot">&lt;-</span> <span class="fu">get_coords</span>(mall_name) <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Just in case I will write this data to a rds file for later usage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(mall_list_coords, <span class="st">"data/rds/mall_list_coords.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mall <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/mall_list_coords.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="primary-school-list" class="level3">
<h3 class="anchored" data-anchor-id="primary-school-list">Primary school list</h3>
<p>Firstly since the data Generalinformationofschools.csv file include the list of all schools I would need to extract data to get the necessary information such as name and address. This is done using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>school_list <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/non-geo/Generalinformationofschools.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(mainlevel_code <span class="sc">==</span> <span class="st">'PRIMARY'</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span>,<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next similarly to the <code>resale</code> data or the <code>mall</code> data this address list would be feed into the <code>get_coords()</code> function creating a new list of coordinations as <code>longitude</code> and <code>latitude</code> which is not <code>sf</code> type and would be hard for later analysis, the code chunk below would use the <code>st_as_sf()</code> to convert it to a <strong>POINT</strong> geometric instead and <code>st_transform()</code> used to make sure the crs is in correct format. All of this would be done in the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>school_list_address <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">unique</span>(school_list<span class="sc">$</span>address))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>school_list_coords <span class="ot">&lt;-</span> <span class="fu">get_coords</span>(school_list_address) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Just in case I will also write this data to a rds file for later usage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(school_list_coords, <span class="st">"data/rds/school_list_coords.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>primary_school <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/school_list_coords.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mrt" class="level3">
<h3 class="anchored" data-anchor-id="mrt">MRT</h3>
<p>Since MRT data is already in geographical points I just need to load it in using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>MRT <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geo/LTAMRTStationExitGEOJSON.geojson"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="preschool-location" class="level3">
<h3 class="anchored" data-anchor-id="preschool-location">Preschool location</h3>
<p>Preschool data is already in geographical points I just need to load it in using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>preschoolslocation <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/geo/PreSchoolsLocation.geojson"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="kindergartens" class="level3">
<h3 class="anchored" data-anchor-id="kindergartens">Kindergartens</h3>
<p>Kindergartens data is already in geographical points I just need to load it in using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>kindergartens <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geo/Kindergartens.kml"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="supermarkets" class="level3">
<h3 class="anchored" data-anchor-id="supermarkets">Supermarkets</h3>
<p>Supermarkets data is already in geographical points I just need to load it in using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>supermarkets <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geo/SupermarketsKML.kml"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="eldercare-center" class="level3">
<h3 class="anchored" data-anchor-id="eldercare-center">Eldercare center</h3>
<p>Elder care center data is already in geographical points I just need to load it in using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>eldercare <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geo"</span>,</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">layer =</span> <span class="st">"ELDERCARE"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="childcare-center" class="level3">
<h3 class="anchored" data-anchor-id="childcare-center">Childcare center</h3>
<p>Childcare center data is already in geographical points I just need to load it in using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>childcare <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geo"</span>,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">layer =</span> <span class="st">"CHILDCARE"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="bus-stops" class="level3">
<h3 class="anchored" data-anchor-id="bus-stops">Bus Stops</h3>
<p>Bus Stops data is already in geographical points I just need to load it in using the code chunk below. However I do notice during analysis that some of the Bus stops especially ‘46239’, ‘46609’, ‘47701’, ‘46211’, ‘46219’ are located outside of Singapore hence I would remove them from this analysis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>busstop <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geo"</span>,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">layer =</span> <span class="st">"BusStop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>BUS_STOP_N <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'46239'</span>,<span class="st">'46609'</span>,<span class="st">'47701'</span>,<span class="st">'46211'</span>,<span class="st">'46219'</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="chas-clinics" class="level3">
<h3 class="anchored" data-anchor-id="chas-clinics">CHAS clinics</h3>
<p>CHAS clinics data is already in geographical points I just need to load it in using the code chunk below. However I do notice during analysis that one of the clinic ‘kml_271’ is somehow located outside of Singapore hence I would remove them from this analysis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>CHAS <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geo/CHASClinics.kml"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Name <span class="sc">!=</span> <span class="st">'kml_271'</span>)<span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="market-and-foodcentres" class="level3">
<h3 class="anchored" data-anchor-id="market-and-foodcentres">Market and foodcentres</h3>
<p>Market and foodcentres data is already in geographical points I just need to load it in using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>market_foodcentre <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geo/NEAMarketandFoodCentre.geojson"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="parks" class="level3">
<h3 class="anchored" data-anchor-id="parks">Parks</h3>
<p>Parks data is already in geographical points I just need to load it in using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>park <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geo/ParkFacilitiesGEOJSON.geojson"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="second-phase-of-data-preparation-and-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="second-phase-of-data-preparation-and-wrangling">3.2 Second phase of data preparation and wrangling</h2>
<p>Once all the data are loaded in I will move on to the next step of calculating the geographical proximity and the number of facilities within a radius of HDB units.</p>
<p>First I will create 2 buffer zone data for these unit at 1000 m or 1 km and 350 m separately. The code chunk below will be for this purpose</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>buffer_1km_HDB  <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(resale_final,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">dist =</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>buffer_350m_HDB  <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(resale_final,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">dist =</span> <span class="dv">350</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once the buffer zones are created, new columns are created for the <code>resale_final</code> and they each represent the number of facilities within a radius of HDB units either 350 m or 1 km. The function to calculate this number would be based on the <code>lengths(st_intersects(bufferzone, facility))</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>resale_final<span class="sc">$</span>within_350m_kindergartens <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(buffer_350m_HDB, kindergartens))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>resale_final<span class="sc">$</span>within_350m_childcare <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(buffer_350m_HDB, childcare))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>resale_final<span class="sc">$</span>within_350mm_busstop <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(buffer_350m_HDB, busstop))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>resale_final<span class="sc">$</span>within_350mm_preschoolslocation <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(buffer_350m_HDB, preschoolslocation))</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>resale_final<span class="sc">$</span>within_1km_chas <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(buffer_1km_HDB, CHAS))</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>resale_final<span class="sc">$</span>within_1km_primary_school <span class="ot">&lt;-</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(buffer_1km_HDB, primary_school))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next new columns are created for the <code>resale_final</code> and they each represent the minimum distance from a unit to another region (CBD) or to another facility. This calculation is based on the <code>min(st_distance(HDB, location)))/1000</code> or is in kilometer shortest distance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>resale_final <span class="ot">&lt;-</span> resale_final <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prox_CBD =</span>  <span class="fu">as.numeric</span>(<span class="fu">min</span>(<span class="fu">st_distance</span>(geometry, CBD)))<span class="sc">/</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prox_eldercare =</span>  <span class="fu">as.numeric</span>(<span class="fu">min</span>(<span class="fu">st_distance</span>(geometry, eldercare)))<span class="sc">/</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prox_market_foodcentre =</span>  <span class="fu">as.numeric</span>(<span class="fu">min</span>(<span class="fu">st_distance</span>(geometry, market_foodcentre)))<span class="sc">/</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prox_MRT =</span>  <span class="fu">as.numeric</span>(<span class="fu">min</span>(<span class="fu">st_distance</span>(geometry, MRT)))<span class="sc">/</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prox_park =</span>  <span class="fu">as.numeric</span>(<span class="fu">min</span>(<span class="fu">st_distance</span>(geometry, park)))<span class="sc">/</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prox_mall =</span>  <span class="fu">as.numeric</span>(<span class="fu">min</span>(<span class="fu">st_distance</span>(geometry, mall)))<span class="sc">/</span><span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prox_supermarkets =</span>  <span class="fu">as.numeric</span>(<span class="fu">min</span>(<span class="fu">st_distance</span>(geometry, supermarkets)))<span class="sc">/</span><span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once all this caluclation is done I will write this data to a rds file for later usage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(resale_final, <span class="st">"data/rds/resale_final.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="third-phase-of-data-preparation-and-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="third-phase-of-data-preparation-and-wrangling">3.3 Third phase of data preparation and wrangling</h2>
<p>This will be the final phase to get all the dat needed for the analysis</p>
<p>Firstly, I will be selecting only the columns that is needed for the analysis using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>resale_final <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/resale_final.rds"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(month, resale_price, floor_area_sqm, storey_level, remaining_lease_time,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>         prox_CBD, prox_eldercare, prox_market_foodcentre, prox_MRT,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>         prox_park, prox_mall, prox_supermarkets, within_350m_kindergartens,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>         within_350m_childcare, within_350mm_busstop, </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>         within_350mm_preschoolslocation, within_1km_chas, </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>         within_1km_primary_school)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next I will check for the duplicated point using the sum of multiplicity or <code>sum(multiplicity())</code>, <code>multiplicity()</code> is part of <code>spatstat</code> package to count the number of duplicates for each point in a spatial point pattern</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">multiplicity</span>(resale_final) <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The above code would return a results of 12 duplicated units points, this has been cut off from running since it taking a long time to run. This indicates that there are units that could be in the same building block or very unlikely, sold multiple time during the study period.</p>
</div>
</div>
<p>To resolve this issue I will be using <code>st_jitter()</code> to which techincally moving points within a short distance to address overlapping points issue. In this case I will move them within a 5 meter radius. The code chunk below is used to do this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>resale_final <span class="ot">&lt;-</span> <span class="fu">st_jitter</span>(resale_final, <span class="at">amount =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once this is done we could no longer see any duplicate point by rerunning the previous code/</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">multiplicity</span>(resale_final) <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Now, since the task specifically specify that I would be using HDB resale transaction records in 2023 to predict HDB resale prices between July-September 2024. I will split them into 2 part call <code>resale_main</code> and <code>resale_check</code> filtered by the specific period.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>resale_main <span class="ot">&lt;-</span> resale_final <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(month <span class="sc">&gt;=</span> <span class="st">"2023-01"</span> <span class="sc">&amp;</span> month <span class="sc">&lt;=</span> <span class="st">"2023-12"</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>resale_check <span class="ot">&lt;-</span> resale_final <span class="sc">%&gt;%</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(month <span class="sc">&gt;=</span> <span class="st">"2024-07"</span> <span class="sc">&amp;</span> month <span class="sc">&lt;=</span> <span class="st">"2024-09"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, they would be turn into the data that would be used for training and data for testing and prediction specifically call <code>train_data</code> and <code>test_data</code>. The code chunk below will be doing the above and I will write this data to a rds file for later usage.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> resale_main</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>coords_train <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(resale_main)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">write_rds</span>(train_data, <span class="st">"data/rds/train_data.rds"</span>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>coords_train <span class="ot">&lt;-</span> <span class="fu">write_rds</span>(coords_train, <span class="st">"data/rds/coords_train.rds"</span> )</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> resale_check</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>coords_test <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(resale_check)</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> <span class="fu">write_rds</span>(test_data, <span class="st">"data/rds/test_data.rds"</span>)</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>coords_test <span class="ot">&lt;-</span> <span class="fu">write_rds</span>(coords_test, <span class="st">"data/rds/coords_test.rds"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next I would want to check how is the data is doing and see if there was any issue with <strong>Collinearity</strong>. To do this I would first create a new data set without its geometry using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>resale_main_nogeo <span class="ot">&lt;-</span> resale_main <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This data would then be checked for <strong>Collinearity</strong> using the <code>corrplot()</code> of <code>corrplot</code> package in the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>corrplot<span class="sc">::</span><span class="fu">corrplot</span>(<span class="fu">cor</span>(resale_main_nogeo[, <span class="dv">2</span><span class="sc">:</span><span class="dv">17</span>]), </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">diag =</span> <span class="cn">FALSE</span>, </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">order =</span> <span class="st">"AOE"</span>,</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">tl.pos =</span> <span class="st">"td"</span>, </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">tl.cex =</span> <span class="fl">0.5</span>, </span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">method =</span> <span class="st">"number"</span>, </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">type =</span> <span class="st">"upper"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project03_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid figure-img" width="900"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Since none of the correlation is higher/lower than +- 0.7, I will be keeping all the variables for this study</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/train_data.rds"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/test_data.rds"</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>coords_train <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/coords_train.rds"</span> )</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>coords_test <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/coords_test.rds"</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="model-bulding-and-callibation" class="level1">
<h1>4. Model bulding and callibation</h1>
<section id="non-spatial-multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="non-spatial-multiple-linear-regression">4.1 Non-spatial multiple linear regression</h2>
<p>The code chunk below will build the multiple linear regression using the <code>lm()</code> of <code>stats</code> package to fit linear multivariate models, all the previously mentioned predictors and variables are included to build this model. Then we would use the <code>ols_regress()</code> of <code>olsrr</code> to perform the Ordinary least squares regression</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>price_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(resale_price <span class="sc">~</span> floor_area_sqm <span class="sc">+</span> storey_level <span class="sc">+</span> </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>                  remaining_lease_time <span class="sc">+</span> prox_CBD <span class="sc">+</span> prox_eldercare <span class="sc">+</span> </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>                  prox_market_foodcentre <span class="sc">+</span> prox_MRT <span class="sc">+</span> prox_park <span class="sc">+</span> prox_mall <span class="sc">+</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>                  prox_supermarkets <span class="sc">+</span> within_350m_kindergartens <span class="sc">+</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>                  within_350m_childcare <span class="sc">+</span> within_350mm_busstop <span class="sc">+</span> </span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>                  within_350mm_preschoolslocation <span class="sc">+</span> within_1km_chas <span class="sc">+</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>                  within_1km_primary_school,</span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">data=</span>train_data)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>olsrr<span class="sc">::</span><span class="fu">ols_regress</span>(price_mlr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              Model Summary                                
--------------------------------------------------------------------------
R                           0.875       RMSE                    42719.098 
R-Squared                   0.766       MSE                1829816217.009 
Adj. R-Squared              0.766       Coef. Var                  10.386 
Pred R-Squared              0.764       AIC                    153589.830 
MAE                     31029.976       SBC                    153711.456 
--------------------------------------------------------------------------
 RMSE: Root Mean Square Error 
 MSE: Mean Square Error 
 MAE: Mean Absolute Error 
 AIC: Akaike Information Criteria 
 SBC: Schwarz Bayesian Criteria 

                                     ANOVA                                      
-------------------------------------------------------------------------------
                    Sum of                                                     
                   Squares          DF       Mean Square       F          Sig. 
-------------------------------------------------------------------------------
Regression    3.800424e+13          16      2.375265e+12    1298.089    0.0000 
Residual      1.159738e+13        6338    1829816217.009                       
Total         4.960161e+13        6354                                         
-------------------------------------------------------------------------------

                                                    Parameter Estimates                                                      
----------------------------------------------------------------------------------------------------------------------------
                          model           Beta    Std. Error    Std. Beta       t        Sig           lower          upper 
----------------------------------------------------------------------------------------------------------------------------
                    (Intercept)    -159037.708      7560.767                 -21.035    0.000    -173859.370    -144216.045 
                 floor_area_sqm       5268.250        97.413        0.338     54.082    0.000       5077.287       5459.213 
                   storey_level       9668.810       325.058        0.200     29.745    0.000       9031.587      10306.033 
           remaining_lease_time        373.707         3.791        0.849     98.581    0.000        366.276        381.139 
                       prox_CBD      -9842.643       183.872       -0.457    -53.530    0.000     -10203.095      -9482.191 
                 prox_eldercare       3837.286      1118.404        0.024      3.431    0.001       1644.835       6029.736 
         prox_market_foodcentre     -15096.642       603.961       -0.235    -24.996    0.000     -16280.609     -13912.674 
                       prox_MRT     -30707.664      1653.726       -0.126    -18.569    0.000     -33949.527     -27465.801 
                      prox_park     -17357.348      2233.627       -0.050     -7.771    0.000     -21736.013     -12978.683 
                      prox_mall     -16171.291      1665.034       -0.066     -9.712    0.000     -19435.321     -12907.260 
              prox_supermarkets      25146.697      3034.004        0.055      8.288    0.000      19199.023      31094.371 
      within_350m_kindergartens       5560.911       897.766        0.056      6.194    0.000       3800.986       7320.837 
          within_350m_childcare        959.410       217.318        0.032      4.415    0.000        533.392       1385.427 
           within_350mm_busstop        572.749       213.877        0.017      2.678    0.007        153.477        992.020 
within_350mm_preschoolslocation      -2078.563       355.906       -0.059     -5.840    0.000      -2776.259      -1380.866 
                within_1km_chas       -358.466        88.349       -0.033     -4.057    0.000       -531.660       -185.272 
      within_1km_primary_school       4499.554       496.240        0.071      9.067    0.000       3526.756       5472.353 
----------------------------------------------------------------------------------------------------------------------------</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The model has an Adj. R-Squared of 0.766 which is not bad but also not great and I believe we could do better than this, ANOVA results show that the differences between variables are statistically significant and are unlikely to be due to chance</p>
<p>Its AIC (Akaike Information Criteria) 153589.830 would be kept in mind for later comparison of other models</p>
</div>
</div>
<p>Next we will calculating the variance inflation factor (VIF) using the <code>check_collinearity()</code> of the <code>performance</code> package, and then explore its results within the table created by the <code>kable()</code> from either <code>kableExtra</code> or <code>knitr</code> package</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>vif <span class="ot">&lt;-</span> <span class="fu">check_collinearity</span>(price_mlr)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(vif, </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Variance Inflation Factor (VIF) Results"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">font_size =</span> <span class="dv">18</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small" data-quarto-postprocess="true">
<caption>Variance Inflation Factor (VIF) Results</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">VIF</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">VIF_CI_low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">VIF_CI_high</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SE_factor</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Tolerance</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Tolerance_CI_low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Tolerance_CI_high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">floor_area_sqm</td>
<td style="text-align: right;">1.057888</td>
<td style="text-align: right;">1.036092</td>
<td style="text-align: right;">1.092846</td>
<td style="text-align: right;">1.028537</td>
<td style="text-align: right;">0.9452798</td>
<td style="text-align: right;">0.9150417</td>
<td style="text-align: right;">0.9651653</td>
</tr>
<tr class="even">
<td style="text-align: left;">storey_level</td>
<td style="text-align: right;">1.219417</td>
<td style="text-align: right;">1.186839</td>
<td style="text-align: right;">1.257676</td>
<td style="text-align: right;">1.104272</td>
<td style="text-align: right;">0.8200639</td>
<td style="text-align: right;">0.7951171</td>
<td style="text-align: right;">0.8425746</td>
</tr>
<tr class="odd">
<td style="text-align: left;">remaining_lease_time</td>
<td style="text-align: right;">2.012568</td>
<td style="text-align: right;">1.941069</td>
<td style="text-align: right;">2.089498</td>
<td style="text-align: right;">1.418650</td>
<td style="text-align: right;">0.4968776</td>
<td style="text-align: right;">0.4785837</td>
<td style="text-align: right;">0.5151799</td>
</tr>
<tr class="even">
<td style="text-align: left;">prox_CBD</td>
<td style="text-align: right;">1.978201</td>
<td style="text-align: right;">1.908356</td>
<td style="text-align: right;">2.053416</td>
<td style="text-align: right;">1.406485</td>
<td style="text-align: right;">0.5055098</td>
<td style="text-align: right;">0.4869934</td>
<td style="text-align: right;">0.5240111</td>
</tr>
<tr class="odd">
<td style="text-align: left;">prox_eldercare</td>
<td style="text-align: right;">1.314164</td>
<td style="text-align: right;">1.276684</td>
<td style="text-align: right;">1.356721</td>
<td style="text-align: right;">1.146370</td>
<td style="text-align: right;">0.7609401</td>
<td style="text-align: right;">0.7370710</td>
<td style="text-align: right;">0.7832795</td>
</tr>
<tr class="even">
<td style="text-align: left;">prox_market_foodcentre</td>
<td style="text-align: right;">2.400750</td>
<td style="text-align: right;">2.310604</td>
<td style="text-align: right;">2.497097</td>
<td style="text-align: right;">1.549435</td>
<td style="text-align: right;">0.4165364</td>
<td style="text-align: right;">0.4004650</td>
<td style="text-align: right;">0.4327872</td>
</tr>
<tr class="odd">
<td style="text-align: left;">prox_MRT</td>
<td style="text-align: right;">1.255822</td>
<td style="text-align: right;">1.221328</td>
<td style="text-align: right;">1.295691</td>
<td style="text-align: right;">1.120634</td>
<td style="text-align: right;">0.7962914</td>
<td style="text-align: right;">0.7717892</td>
<td style="text-align: right;">0.8187806</td>
</tr>
<tr class="even">
<td style="text-align: left;">prox_park</td>
<td style="text-align: right;">1.102899</td>
<td style="text-align: right;">1.077209</td>
<td style="text-align: right;">1.137135</td>
<td style="text-align: right;">1.050190</td>
<td style="text-align: right;">0.9067016</td>
<td style="text-align: right;">0.8794028</td>
<td style="text-align: right;">0.9283247</td>
</tr>
<tr class="odd">
<td style="text-align: left;">prox_mall</td>
<td style="text-align: right;">1.260166</td>
<td style="text-align: right;">1.225447</td>
<td style="text-align: right;">1.300231</td>
<td style="text-align: right;">1.122571</td>
<td style="text-align: right;">0.7935462</td>
<td style="text-align: right;">0.7690939</td>
<td style="text-align: right;">0.8160285</td>
</tr>
<tr class="even">
<td style="text-align: left;">prox_supermarkets</td>
<td style="text-align: right;">1.198851</td>
<td style="text-align: right;">1.167381</td>
<td style="text-align: right;">1.236238</td>
<td style="text-align: right;">1.094920</td>
<td style="text-align: right;">0.8341322</td>
<td style="text-align: right;">0.8089060</td>
<td style="text-align: right;">0.8566185</td>
</tr>
<tr class="odd">
<td style="text-align: left;">within_350m_kindergartens</td>
<td style="text-align: right;">2.210474</td>
<td style="text-align: right;">2.129463</td>
<td style="text-align: right;">2.297297</td>
<td style="text-align: right;">1.486766</td>
<td style="text-align: right;">0.4523916</td>
<td style="text-align: right;">0.4352942</td>
<td style="text-align: right;">0.4696020</td>
</tr>
<tr class="even">
<td style="text-align: left;">within_350m_childcare</td>
<td style="text-align: right;">1.442154</td>
<td style="text-align: right;">1.398298</td>
<td style="text-align: right;">1.490838</td>
<td style="text-align: right;">1.200897</td>
<td style="text-align: right;">0.6934074</td>
<td style="text-align: right;">0.6707638</td>
<td style="text-align: right;">0.7151550</td>
</tr>
<tr class="odd">
<td style="text-align: left;">within_350mm_busstop</td>
<td style="text-align: right;">1.106823</td>
<td style="text-align: right;">1.080858</td>
<td style="text-align: right;">1.141125</td>
<td style="text-align: right;">1.052056</td>
<td style="text-align: right;">0.9034869</td>
<td style="text-align: right;">0.8763283</td>
<td style="text-align: right;">0.9251906</td>
</tr>
<tr class="even">
<td style="text-align: left;">within_350mm_preschoolslocation</td>
<td style="text-align: right;">2.740045</td>
<td style="text-align: right;">2.633628</td>
<td style="text-align: right;">2.853395</td>
<td style="text-align: right;">1.655308</td>
<td style="text-align: right;">0.3649575</td>
<td style="text-align: right;">0.3504598</td>
<td style="text-align: right;">0.3797043</td>
</tr>
<tr class="odd">
<td style="text-align: left;">within_1km_chas</td>
<td style="text-align: right;">1.783973</td>
<td style="text-align: right;">1.723491</td>
<td style="text-align: right;">1.849511</td>
<td style="text-align: right;">1.335655</td>
<td style="text-align: right;">0.5605466</td>
<td style="text-align: right;">0.5406835</td>
<td style="text-align: right;">0.5802176</td>
</tr>
<tr class="even">
<td style="text-align: left;">within_1km_primary_school</td>
<td style="text-align: right;">1.681112</td>
<td style="text-align: right;">1.625605</td>
<td style="text-align: right;">1.741544</td>
<td style="text-align: right;">1.296577</td>
<td style="text-align: right;">0.5948444</td>
<td style="text-align: right;">0.5742032</td>
<td style="text-align: right;">0.6151557</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>VIF itself is below 5 and tolerance is within the 0.25 to 4 hence indicating that there is unlikely any issue with multicollinearity with this regression model</p>
</div>
</div>
<p>The plot below is to better visualize the VIF</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vif) <span class="sc">+</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project03_files/figure-html/unnamed-chunk-52-1.png" class="img-fluid figure-img" width="1200"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="geographically-weighted-regression-with-gwr-method" class="level2">
<h2 class="anchored" data-anchor-id="geographically-weighted-regression-with-gwr-method">4.2 Geographically Weighted Regression with gwr method</h2>
<p>Next I would try out the Geographically Weighted Regression or gwr method using <code>GWmodel</code> package, however just running the model and then calibrating them would take a lot of time hence I would be calibrating the model at the same time.</p>
<p>The first step is to calibrate the model by calculating the adaptive bandwidth based on the training data or <code>train_data</code>. To do this <code>bw.gwr()</code> would be used in the code chunk below creating the <code>bw_adaptive</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>bw_adaptive <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(resale_price <span class="sc">~</span> floor_area_sqm <span class="sc">+</span> storey_level <span class="sc">+</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>                        remaining_lease_time <span class="sc">+</span> prox_CBD <span class="sc">+</span> prox_eldercare <span class="sc">+</span> </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>                        prox_market_foodcentre <span class="sc">+</span> prox_MRT <span class="sc">+</span> prox_park <span class="sc">+</span> prox_mall <span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>                        prox_supermarkets <span class="sc">+</span> within_350m_kindergartens <span class="sc">+</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>                        within_350m_childcare <span class="sc">+</span> within_350mm_busstop <span class="sc">+</span> </span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>                        within_350mm_preschoolslocation <span class="sc">+</span> within_1km_chas <span class="sc">+</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>                        within_1km_primary_school,</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data=</span>train_data,</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">approach=</span><span class="st">"CV"</span>,</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">kernel=</span><span class="st">"gaussian"</span>,</span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>                      <span class="at">adaptive=</span><span class="cn">TRUE</span>,</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>                      <span class="at">longlat=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once this has finished running I will write this data to a rds file for later usage</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(bw_adaptive, <span class="st">"data/rds/bw_adaptive.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>bw_adaptive <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/bw_adaptive.rds"</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>bw_adaptive</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38</code></pre>
</div>
</div>
<p>The results is that the calibrated adaptive bandwidth for the model should be 38</p>
<p>The next step is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>gwr_adaptive <span class="ot">&lt;-</span> <span class="fu">gwr.basic</span>(<span class="at">formula =</span> resale_price <span class="sc">~</span> floor_area_sqm <span class="sc">+</span> storey_level <span class="sc">+</span> </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                            remaining_lease_time <span class="sc">+</span> prox_CBD <span class="sc">+</span> prox_eldercare <span class="sc">+</span> </span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                            prox_market_foodcentre <span class="sc">+</span> prox_MRT <span class="sc">+</span> prox_park <span class="sc">+</span> prox_mall <span class="sc">+</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>                            within_350m_childcare <span class="sc">+</span> within_350mm_busstop <span class="sc">+</span> </span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>                            within_350mm_preschoolslocation <span class="sc">+</span> within_1km_chas <span class="sc">+</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>                            within_1km_primary_school,</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data=</span>train_data,</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">bw=</span>bw_adaptive, </span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>                          <span class="at">kernel =</span> <span class="st">'gaussian'</span>, </span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">adaptive=</span><span class="cn">TRUE</span>,</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">longlat =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once this has finished running I will write this data to a rds file for later usage</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(gwr_adaptive, <span class="st">"data/rds/gwr_adaptive.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>gwr_adaptive <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/gwr_adaptive.rds"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>gwr_adaptive</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ***********************************************************************
   *                       Package   GWmodel                             *
   ***********************************************************************
   Program starts at: 2024-11-09 21:02:57.55229 
   Call:
   gwr.basic(formula = resale_price ~ floor_area_sqm + storey_level + 
    remaining_lease_time + prox_CBD + prox_eldercare + prox_market_foodcentre + 
    prox_MRT + prox_park + prox_mall + within_350m_childcare + 
    within_350mm_busstop + within_350mm_preschoolslocation + 
    within_1km_chas + within_1km_primary_school, data = train_data, 
    bw = bw_adaptive, kernel = "gaussian", adaptive = TRUE, longlat = FALSE)

   Dependent (y) variable:  resale_price
   Independent variables:  floor_area_sqm storey_level remaining_lease_time prox_CBD prox_eldercare prox_market_foodcentre prox_MRT prox_park prox_mall within_350m_childcare within_350mm_busstop within_350mm_preschoolslocation within_1km_chas within_1km_primary_school
   Number of data points: 6355
   ***********************************************************************
   *                    Results of Global Regression                     *
   ***********************************************************************

   Call:
    lm(formula = formula, data = data)

   Residuals:
    Min      1Q  Median      3Q     Max 
-345595  -26786   -3503   21956  535104 

   Coefficients:
                                     Estimate Std. Error t value Pr(&gt;|t|)    
   (Intercept)                     -1.510e+05  7.585e+03 -19.904  &lt; 2e-16 ***
   floor_area_sqm                   5.279e+03  9.815e+01  53.785  &lt; 2e-16 ***
   storey_level                     9.902e+03  3.270e+02  30.278  &lt; 2e-16 ***
   remaining_lease_time             3.674e+02  3.765e+00  97.587  &lt; 2e-16 ***
   prox_CBD                        -9.436e+03  1.805e+02 -52.279  &lt; 2e-16 ***
   prox_eldercare                   4.321e+03  1.127e+03   3.835 0.000127 ***
   prox_market_foodcentre          -1.617e+04  5.960e+02 -27.126  &lt; 2e-16 ***
   prox_MRT                        -2.974e+04  1.663e+03 -17.888  &lt; 2e-16 ***
   prox_park                       -1.602e+04  2.242e+03  -7.145 9.97e-13 ***
   prox_mall                       -1.416e+04  1.664e+03  -8.507  &lt; 2e-16 ***
   within_350m_childcare            8.335e+02  2.177e+02   3.830 0.000130 ***
   within_350mm_busstop             5.856e+02  2.157e+02   2.715 0.006637 ** 
   within_350mm_preschoolslocation -8.841e+02  2.610e+02  -3.387 0.000711 ***
   within_1km_chas                 -4.614e+02  8.846e+01  -5.216 1.89e-07 ***
   within_1km_primary_school        4.307e+03  4.971e+02   8.664  &lt; 2e-16 ***

   ---Significance stars
   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 
   Residual standard error: 43140 on 6340 degrees of freedom
   Multiple R-squared: 0.7622
   Adjusted R-squared: 0.7616 
   F-statistic:  1451 on 14 and 6340 DF,  p-value: &lt; 2.2e-16 
   ***Extra Diagnostic information
   Residual sum of squares: 1.17974e+13
   Sigma(hat): 43092.71
   AIC:  153694.5
   AICc:  153694.6
   BIC:  147587.7
   ***********************************************************************
   *          Results of Geographically Weighted Regression              *
   ***********************************************************************

   *********************Model calibration information*********************
   Kernel function: gaussian 
   Adaptive bandwidth: 38 (number of nearest neighbours)
   Regression points: the same locations as observations are used.
   Distance metric: Euclidean distance metric is used.

   ****************Summary of GWR coefficient estimates:******************
                                          Min.     1st Qu.      Median
   Intercept                       -4.0054e+07 -2.9240e+05 -7.0469e+04
   floor_area_sqm                  -5.9340e+04  2.5181e+03  3.3501e+03
   storey_level                    -1.5804e+03  5.6834e+03  7.5921e+03
   remaining_lease_time            -1.9320e+03  1.8958e+02  2.9800e+02
   prox_CBD                        -1.3404e+06 -2.7368e+04 -5.5153e+03
   prox_eldercare                  -7.1923e+05 -5.2017e+03  1.2601e+04
   prox_market_foodcentre          -4.4488e+06 -2.4613e+04  3.9812e+03
   prox_MRT                        -1.1081e+06 -7.2842e+04 -3.3150e+04
   prox_park                       -5.8831e+05 -3.0059e+04  2.7048e+02
   prox_mall                       -1.8786e+06 -4.2443e+04 -6.8576e+03
   within_350m_childcare           -5.3707e+04 -2.7396e+03 -1.3046e+02
   within_350mm_busstop            -1.9138e+04 -1.1816e+03  1.9434e+02
   within_350mm_preschoolslocation -3.4975e+04 -2.7861e+03 -2.1528e+02
   within_1km_chas                 -1.2560e+04 -1.2234e+03  1.3256e+02
   within_1km_primary_school       -3.5193e+05 -7.9389e+03 -1.0362e+02
                                       3rd Qu.       Max.
   Intercept                        1.8794e+05 6319227.82
   floor_area_sqm                   4.4999e+03  127881.24
   storey_level                     9.2998e+03   19478.85
   remaining_lease_time             4.3956e+02     794.34
   prox_CBD                         1.8830e+04 5131948.02
   prox_eldercare                   4.3843e+04  877257.18
   prox_market_foodcentre           3.7015e+04  625951.00
   prox_MRT                        -6.2888e+02  901122.86
   prox_park                        2.7799e+04 1112226.80
   prox_mall                        2.2010e+04  666309.80
   within_350m_childcare            2.7012e+03   31247.77
   within_350mm_busstop             1.6702e+03   13729.73
   within_350mm_preschoolslocation  1.7522e+03   29700.89
   within_1km_chas                  1.7448e+03   27523.38
   within_1km_primary_school        4.9770e+03  456192.00
   ************************Diagnostic information*************************
   Number of data points: 6355 
   Effective number of parameters (2trace(S) - trace(S'S)): 1168.128 
   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 5186.872 
   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): 146751.4 
   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): 145452.5 
   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): 146518.1 
   Residual sum of squares: 2.788363e+12 
   R-square value:  0.9437848 
   Adjusted R-square value:  0.9311223 

   ***********************************************************************
   Program stops at: 2024-11-09 21:03:19.81276 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Interestingly this gwr.basic() also include the results of another linear regression hence we could quickly compare this result of the GWR model with the previously ran linear model. In this case the Adjusted R-square value of the GWR model is 0.9311223 sinificantly better than 0.76 of the Multilinear regression model. In addition to this its AIC is also at 146751.4 lower than 153694.5 in this model ore the previously recorded 153589.830.</p>
<p>Overall this Geographically Weighted Regression model seems to perform significantly better than the Multilinear regression model</p>
</div>
</div>
<p>Next I’ll calculate the calibration bandwidth for the testing data or <code>test_data</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>gwr_bw_test_adaptive <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(resale_price <span class="sc">~</span> floor_area_sqm <span class="sc">+</span> storey_level <span class="sc">+</span> </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>                                 remaining_lease_time <span class="sc">+</span> prox_CBD <span class="sc">+</span> prox_eldercare <span class="sc">+</span> </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>                                 prox_market_foodcentre <span class="sc">+</span> prox_MRT <span class="sc">+</span> prox_park <span class="sc">+</span> prox_mall <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>                                 prox_supermarkets <span class="sc">+</span> within_350m_kindergartens <span class="sc">+</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>                                 within_350m_childcare <span class="sc">+</span> within_350mm_busstop <span class="sc">+</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>                                 within_350mm_preschoolslocation <span class="sc">+</span> within_1km_chas <span class="sc">+</span></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>                                 within_1km_primary_school,</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>                               <span class="at">data=</span>test_data,</span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>                               <span class="at">approach=</span><span class="st">"CV"</span>,</span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>                               <span class="at">kernel=</span><span class="st">"gaussian"</span>,</span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>                               <span class="at">adaptive=</span><span class="cn">TRUE</span>,</span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>                               <span class="at">longlat=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once this has finished running I will write this data to a rds file for later usage</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(gwr_bw_test_adaptive, <span class="st">"data/rds/gwr_bw_test_adaptive.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>gwr_bw_test_adaptive <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/gwr_bw_test_adaptive.rds"</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>gwr_bw_test_adaptive</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 287</code></pre>
</div>
</div>
<p>The results is that the calibrated adaptive bandwidth for the test data should be 38</p>
<p>Next I would attempt to predict the data based on the <code>train_data</code> and <code>test_data</code> to have something for comparison</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>gwr_pred <span class="ot">&lt;-</span> <span class="fu">gwr.predict</span>(resale_price <span class="sc">~</span> floor_area_sqm <span class="sc">+</span> storey_level <span class="sc">+</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>                          remaining_lease_time <span class="sc">+</span> prox_CBD <span class="sc">+</span> prox_eldercare <span class="sc">+</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>                          prox_market_foodcentre <span class="sc">+</span> prox_MRT <span class="sc">+</span> prox_park <span class="sc">+</span> prox_mall <span class="sc">+</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>                          prox_supermarkets <span class="sc">+</span> within_350m_kindergartens <span class="sc">+</span></span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>                          within_350m_childcare <span class="sc">+</span> within_350mm_busstop <span class="sc">+</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>                          within_350mm_preschoolslocation <span class="sc">+</span> within_1km_chas <span class="sc">+</span></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>                          within_1km_primary_school,</span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data=</span>train_data,</span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>                        <span class="at">predictdata =</span> test_data,</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>                        <span class="at">bw=</span><span class="dv">287</span>,</span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>                        <span class="at">kernel =</span> <span class="st">'gaussian'</span>,</span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a>                        <span class="at">adaptive=</span><span class="cn">TRUE</span>,</span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a>                        <span class="at">longlat =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Unfortunately, I was not able to overcame the “no regression point is fixed” error for this <code>gwr.predict()</code> function and unable to showcase them here</p>
</div>
</div>
</section>
<section id="geographically-weighted-random-forest-method-of-spatialml-package" class="level2">
<h2 class="anchored" data-anchor-id="geographically-weighted-random-forest-method-of-spatialml-package">4.3 Geographically Weighted Random Forest method of SpatialML package</h2>
<p>First let drop the geometry column of training data sets</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> train_data <span class="sc">%&gt;%</span> </span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we would run an inital Random Forest model with default setting to check how well the model would turn out using the <code>ranger()</code> of <code>ranger</code> package. In addition, I will reduce the number of tree down to 53 instead of 500 since 500 trees would take a lot of time to run for later calibration</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>rf <span class="ot">&lt;-</span> <span class="fu">ranger</span>(resale_price <span class="sc">~</span> floor_area_sqm <span class="sc">+</span> storey_level <span class="sc">+</span> </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>               remaining_lease_time <span class="sc">+</span> prox_CBD <span class="sc">+</span> prox_eldercare <span class="sc">+</span> </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>               prox_market_foodcentre <span class="sc">+</span> prox_MRT <span class="sc">+</span> prox_park <span class="sc">+</span> prox_mall <span class="sc">+</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>               prox_supermarkets <span class="sc">+</span> within_350m_kindergartens <span class="sc">+</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>               within_350m_childcare <span class="sc">+</span> within_350mm_busstop <span class="sc">+</span> </span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>               within_350mm_preschoolslocation <span class="sc">+</span> within_1km_chas <span class="sc">+</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>               within_1km_primary_school,</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">num.trees =</span> <span class="dv">53</span>,</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">mtry =</span> <span class="dv">5</span>,</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">importance =</span> <span class="st">"impurity"</span>,</span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">data=</span>train_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once this has finished running I will write this data to a rds file for later usage</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(rf, <span class="st">"data/rds/rf.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>rf <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/rf.rds"</span>)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>rf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Ranger result

Call:
 ranger(resale_price ~ floor_area_sqm + storey_level + remaining_lease_time +      prox_CBD + prox_eldercare + prox_market_foodcentre + prox_MRT +      prox_park + prox_mall + prox_supermarkets + within_350m_kindergartens +      within_350m_childcare + within_350mm_busstop + within_350mm_preschoolslocation +      within_1km_chas + within_1km_primary_school, num.trees = 53,      mtry = 5, importance = "impurity", data = train_data) 

Type:                             Regression 
Number of trees:                  53 
Sample size:                      6355 
Number of independent variables:  16 
Mtry:                             5 
Target node size:                 5 
Variable importance mode:         impurity 
Splitrule:                        variance 
OOB prediction error (MSE):       633848167 
R squared (OOB):                  0.9188036 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This model return a OOB prediction error (MSE) of 636284892 and R squared (OOB) of 0.9184915, based on R squared alone this is a pretty good model.</p>
</div>
</div>
<p>Next I will attempt to calibrate this model using the <code>bw_adaptive</code> of 38 calculated previously and using the <code>grf()</code> of <code>SpacialML</code> package. This would fit a local version of the Random Forest algorithm, accounting for spatial non-stationarity</p>
<p>The code chunk below show the code for this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>gwRF_adaptive <span class="ot">&lt;-</span> <span class="fu">grf</span>(<span class="at">formula =</span> resale_price <span class="sc">~</span> floor_area_sqm <span class="sc">+</span> storey_level <span class="sc">+</span> </span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>                       remaining_lease_time <span class="sc">+</span> prox_CBD <span class="sc">+</span> prox_eldercare <span class="sc">+</span> </span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>                       prox_market_foodcentre <span class="sc">+</span> prox_MRT <span class="sc">+</span> prox_park <span class="sc">+</span> prox_mall <span class="sc">+</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>                       prox_supermarkets <span class="sc">+</span> within_350m_kindergartens <span class="sc">+</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>                       within_350m_childcare <span class="sc">+</span> within_350mm_busstop <span class="sc">+</span> </span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>                       within_350mm_preschoolslocation <span class="sc">+</span> within_1km_chas <span class="sc">+</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>                       within_1km_primary_school,</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">dframe=</span>train_data,</span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>                     <span class="at">ntree =</span> <span class="dv">53</span>,</span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">bw=</span><span class="dv">38</span>,</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">kernel=</span><span class="st">"adaptive"</span>,</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>                     <span class="at">coords=</span>coords_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once this has finished running I will write this data to a rds file for later usage</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(gwRF_adaptive, <span class="st">"data/rds/gwRF_adaptive.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>gwRF_adaptive <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/gwRF_adaptive.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="1.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>gwRF_adaptive<span class="sc">$</span>LocalModelSummary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$l.VariableImportance
                                      Min          Max        Mean         StD
floor_area_sqm                          0 1.444374e+12 12036908744 38731166250
storey_level                     44363034 2.112563e+11  6706363630 11869802696
remaining_lease_time            312420137 4.938088e+11 19019149378 43649567043
prox_CBD                                0 3.672406e+11  6845136742 20900812241
prox_eldercare                    8062395 1.036893e+12  7365166244 30251391477
prox_market_foodcentre            1815629 4.008882e+11  5927098746 17506021731
prox_MRT                          1871799 9.538612e+11  7094318007 27526763708
prox_park                         3383980 1.442077e+12  6911451236 30460063518
prox_mall                         5138662 6.983204e+11  6454574985 26122120904
prox_supermarkets                       0 1.749969e+12  7368199448 34438841202
within_350m_kindergartens               0 1.154855e+11   987896884  5095969294
within_350m_childcare                   0 1.871588e+11  2809696103 10499177446
within_350mm_busstop                    0 3.120124e+11  3792415215 14101062371
within_350mm_preschoolslocation         0 2.646240e+11  2349973922  7794490999
within_1km_chas                         0 2.410287e+11  4166481778 14685127753
within_1km_primary_school               0 3.213113e+11  2408800082 15656650488

$l.MSE.OOB
[1] 858973085

$l.r.OOB
[1] 0.8899476

$l.MSE.Pred
[1] 82225526

$l.r.Pred
[1] 0.9894652</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The results show both Global ML and Local model with R-squared (Not OOB) at 97.845 and R-squared predicted (Not OOB) at 98.947 respectively, which is quite good. In addition to this all AIC metrics (Not OOB) is at 120401.135 and and 115853.725. This seems to indicate that the local of calibrated version of the Geographically Weighted Random Forest seems to be a better model compared to the model ran by default.</p>
<p>Overall, the Machine Learning method of Geographically Weighted Random Forest is performing the best compared to the Geographically Weighted Regression or the Non-spatial multiple linear regression</p>
<p>The overall trade of is time to run a actually calibrate the model could take a while, for my calibrated Geographically Weighted Random Forest it tooks around 4 hours to finish. Geographically Weighted Regression or the Non-spatial multiple linear regression are performing much better in this regards.</p>
</div>
</div>
<p>Now that the model is inplace, I’ll try to actually predict the data for the July to Sep 2024. Since this the best model, it would be best to use this model to predict data itself to show case its accuracy.</p>
<p>First step is to drop the geometry column of test data sets <code>test_data</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> <span class="fu">cbind</span>(test_data, coords_test) <span class="sc">%&gt;%</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then the data would be predicted using the <code>predict.grf()</code> method of SpatialML package</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>gwRF_pred <span class="ot">&lt;-</span> <span class="fu">predict.grf</span>(gwRF_adaptive, </span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>                         test_data, </span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">x.var.name=</span><span class="st">"X"</span>,</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">y.var.name=</span><span class="st">"Y"</span>, </span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">local.w=</span><span class="dv">1</span>,</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">global.w=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once this has finished running I will write this data to a rds file for later usage</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>GRF_pred <span class="ot">&lt;-</span> <span class="fu">write_rds</span>(gwRF_pred, <span class="st">"data/rds/GRF_pred.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now with the newly created prediction data, they would be mapped to the original <code>test_data</code> using <code>cbind()</code> of base R code</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>GRF_pred <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/GRF_pred.rds"</span>)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>GRF_pred_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(GRF_pred)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>test_data_p <span class="ot">&lt;-</span> <span class="fu">cbind</span>(test_data, GRF_pred_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once this has finished running I will write this data to a rds file for later usage</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(test_data_p, <span class="st">"data/rds/test_data_p.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>test_data_p <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/rds/test_data_p.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s quickly check the root Root Mean Squared Error between the actual resale price and the predicted data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>Metrics<span class="sc">::</span><span class="fu">rmse</span>(test_data_p<span class="sc">$</span>resale_price, </span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>     test_data_p<span class="sc">$</span>GRF_pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 69067.91</code></pre>
</div>
</div>
<p>I would now use the <code>ggplot()</code> of <code>ggplot2</code> package to plot out this grapoh showing prediction data compared to actual data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_light</span>())</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> test_data_p,</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> GRF_pred<span class="sc">/</span><span class="dv">1000</span>,</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> resale_price<span class="sc">/</span><span class="dv">1000</span>)) <span class="sc">+</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Model prediction graph"</span>) <span class="sc">+</span></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Resale price (predicted) thousands $SGD"</span>) <span class="sc">+</span></span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Resale price (actual) thousands $SGD"</span>) <span class="sc">+</span></span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">color =</span> <span class="st">"blue4"</span>, <span class="at">size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Project03_files/figure-html/unnamed-chunk-78-1.png" class="img-fluid figure-img" width="900"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The graph has an diagonal line and the closer the dots are to the line the more accurate the results were. From initial observation it seems that the model has done ok in term of predicting the resale price of HDB units.</p>
<p>However it seems there maybe more or less variables that could be added in or removed to calibrate the model further make its prediction event more accurate. There seems to be more points on the left of the line rather than the right, this signify that the predicted price are often lower than the actual resale prices. This does make sense as all our data actually did not include any economics indicators such as inflation, tax rate raise (2024 in Singapore), etc. Including these metrics in to the model building would greatly improve the model.</p>
<p>In addition, the appearance of outliers, points more on the top left and top rights has also impacted the model itself and its prediction capability. The exclusion of these outliers could potentially be beneficial for the building of a better model as well.</p>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level1">
<h1>5. Conclusion</h1>
<p>On the above exercise I had test out and calibrate 3 different model Non-spatial multiple linear regression, Geographically Weighted Regression and Geographically Weighted Random Forest. Out of 3 of them the Geographically Weighted Random Forest seems to be performing the best and its predict results seem be most accurate.</p>
<p>Outliers seem to be a potential issue that could impact the prediction power and accuracy of model building. In addition more metrics such as economic indicators are likely important and should be considered further.</p>
<p>Overall this has show case the capability of different model building method for geographical data that could be use in the future for common goods to predicts much more than just the data in this study</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>